name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your desired version

      - name: Install dependencies
        run: npm ci

      - name: Fix eslint permissions
        run: chmod +x ./node_modules/.bin/eslint || true

      - name: Run lint
        run: npx eslint src/

      - name: Run tests
        run: npm test

